### ISSUE TITLE
マイグレーションの再適用方法の発見

### ISSUE THREAD

**Issue by YujiOka** [kaede-1008/calendar#3]

**Comment by kaede-1008** [comment]
以下のURLを参考にして解決しました。
https://blog.tstylestudio.com/2017/03/16/sinatra%E3%81%AEdb%E3%81%AB%E5%BE%8C%E3%81%8B%E3%82%89%E3%82%AB%E3%83%A9%E3%83%A0%E3%82%92%E8%BF%BD%E5%8A%A0%E3%80%81%E3%81%A4%E3%81%84%E3%81%A7%E3%81%AB%E5%9E%8B%E3%82%82%E4%BF%AE%E6%AD%A3/
